#!/bin/python3
import sys import socket
from datetime import datetime
#Define Target
if len (sys .argv) == 2:
target = socket.gethostbyname (sys.arg[1]) #Translate hostname to IPv4
else:
print("Invalid amount of arguments.
" )
print ("Syntax: python3 scanner.py <ip>")
#Add a banner print ("." * 50)
print ("Scanning target:
"+target)
print ("Time started:
print (".
* 50)
"+str (datetime. now ( )) )
try:
for port in range (50,85):
§ = socket. socket (socket .AF_ INET, socket.SOCK_ STREAM)
socket. setdefaulttimeout (1)
result = s. connect ex( (target , port))
if result == 0:
print(f"Port {port} is open")
s. close ()
except KeyboardInterrupt:
print ("\nExiting program.
" )
sys.exit ()
except socket.gaierror:
print ("Hostname could not be resolved")
sys.exit ()
except socket.error:
print ( Could not connect to the server")
sys.exit ()
